export DPU_HOST=dpu
export EXT_HOST=tester

export DPU_HOST_ADDR=$DPU_HOST:3444
export EXT_HOST_ADDR=$EXT_HOST:3444
export OPOF_HOST_ADDR=169.254.33.51:3443

export DPU_HOST_IFACES=enp23s0f0v0,enp23s0f0v1,enp23s0f1v0,enp23s0f1v1
export EXT_HOST_IFACES=enp23s0f0np0,enp23s0f1np1

# Destination of traffic generated by the DPU Host (External Host MAC)
export DPU_HOST_DMAC=b8:3f:d2:ba:65:fa,b8:3f:d2:ba:65:fb

# Destination of traffic generated by the External Host (DPU uplink MAC)
export EXT_HOST_DMAC=b8:3f:d2:ba:66:22,b8:3f:d2:ba:66:23
